"""Tests for the brain linker module."""

import os
from pathlib import Path

import pytest

from workspacebrain.core.linker import AI_RULE_FILES, BrainLinker, unlink_project
from workspacebrain.core.scanner import WorkspaceScanner
from workspacebrain.models import BrainConfig


class TestBrainLinker:
    """Tests for BrainLinker class."""

    def test_link_requires_brain(self, temp_workspace: Path) -> None:
        """Test that link fails if brain directory doesn't exist."""
        config = BrainConfig(workspace_path=temp_workspace)
        linker = BrainLinker(config)

        result = linker.link_all()

        assert not result.success
        assert "not found" in result.error.lower()

    def test_link_creates_symlink(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that link creates .brain symlink in projects."""
        # Create and scan a project
        project = temp_workspace_with_brain / "my-app"
        project.mkdir()
        (project / "package.json").write_text('{"name": "my-app"}')
        (project / "next.config.js").write_text("module.exports = {}")

        config = BrainConfig(workspace_path=temp_workspace_with_brain)

        # Scan first to populate manifest
        scanner = WorkspaceScanner(config)
        scanner.scan()

        # Then link
        linker = BrainLinker(config)
        result = linker.link_all()

        assert result.success
        assert len(result.linked_projects) == 1

        # Check symlink was created
        symlink_path = project / ".brain"
        assert symlink_path.is_symlink()

        # Check symlink points to correct relative path
        target = os.readlink(symlink_path)
        assert target == "../brain"

    def test_link_generates_ai_rule_files(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that link generates CLAUDE.md, CURSOR_RULES.md, AI.md."""
        project = temp_workspace_with_brain / "my-app"
        project.mkdir()
        (project / "pyproject.toml").write_text("[project]\n")

        config = BrainConfig(workspace_path=temp_workspace_with_brain)

        scanner = WorkspaceScanner(config)
        scanner.scan()

        linker = BrainLinker(config)
        result = linker.link_all()

        assert result.success

        # Check all AI rule files were generated
        for rule_file in AI_RULE_FILES:
            rule_path = project / rule_file
            assert rule_path.exists(), f"{rule_file} should exist"

            content = rule_path.read_text()
            assert "GENERATED BY WORKSPACEBRAIN" in content
            assert "DO NOT EDIT" in content

        # Check generated files are in result
        assert len(result.generated_files) == 3

    def test_link_single_project(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test linking a single project."""
        project = temp_workspace_with_brain / "single-app"
        project.mkdir()

        config = BrainConfig(workspace_path=temp_workspace_with_brain)
        linker = BrainLinker(config)

        result = linker.link_project(project, "python-be")

        assert result.success
        assert (project / ".brain").is_symlink()

        # Check AI rule files
        for rule_file in AI_RULE_FILES:
            assert (project / rule_file).exists()

    def test_link_is_idempotent(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that linking twice doesn't duplicate or break things."""
        project = temp_workspace_with_brain / "app"
        project.mkdir()
        (project / "pyproject.toml").write_text("[project]\n")

        config = BrainConfig(workspace_path=temp_workspace_with_brain)

        scanner = WorkspaceScanner(config)
        scanner.scan()

        linker = BrainLinker(config)
        linker.link_all()

        # Modify a generated file
        claude_md = project / "CLAUDE.md"
        original_content = claude_md.read_text()

        # Link again (should skip)
        result = linker.link_all()

        assert result.success
        assert "app" in result.skipped_projects

        # Content should be preserved (not regenerated)
        assert claude_md.read_text() == original_content

    def test_link_with_force_regenerates(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that --force regenerates all files."""
        project = temp_workspace_with_brain / "app"
        project.mkdir()
        (project / "pyproject.toml").write_text("[project]\n")

        config = BrainConfig(workspace_path=temp_workspace_with_brain)

        scanner = WorkspaceScanner(config)
        scanner.scan()

        linker = BrainLinker(config)
        linker.link_all()

        # Modify a generated file
        claude_md = project / "CLAUDE.md"
        claude_md.write_text("modified content")

        # Link with force
        config_force = BrainConfig(workspace_path=temp_workspace_with_brain, force=True)
        linker_force = BrainLinker(config_force)
        result = linker_force.link_all()

        assert result.success
        assert "app" in result.linked_projects

        # Content should be regenerated
        assert "GENERATED BY WORKSPACEBRAIN" in claude_md.read_text()

    def test_ai_rule_files_contain_project_type(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that generated AI rule files contain project type info."""
        project = temp_workspace_with_brain / "django-app"
        project.mkdir()
        (project / "pyproject.toml").write_text("[project]\n")
        (project / "manage.py").write_text("#!/usr/bin/env python\n")

        config = BrainConfig(workspace_path=temp_workspace_with_brain)

        scanner = WorkspaceScanner(config)
        scanner.scan()

        linker = BrainLinker(config)
        linker.link_all()

        # Check CLAUDE.md contains project type
        claude_content = (project / "CLAUDE.md").read_text()
        assert "python-be" in claude_content

    def test_symlink_target_is_relative(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that symlink uses relative path, not absolute."""
        project = temp_workspace_with_brain / "my-project"
        project.mkdir()
        (project / "pyproject.toml").write_text("[project]\n")

        config = BrainConfig(workspace_path=temp_workspace_with_brain)

        scanner = WorkspaceScanner(config)
        scanner.scan()

        linker = BrainLinker(config)
        linker.link_all()

        symlink = project / ".brain"
        target = os.readlink(symlink)

        # Should be relative, not absolute
        assert not target.startswith("/")
        assert target == "../brain"


class TestUnlinkProject:
    """Tests for unlink_project function."""

    def test_unlink_removes_symlink(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that unlink removes .brain symlink."""
        project = temp_workspace_with_brain / "app"
        project.mkdir()

        config = BrainConfig(workspace_path=temp_workspace_with_brain)
        linker = BrainLinker(config)
        linker.link_project(project, "python-be")

        assert (project / ".brain").is_symlink()

        result = unlink_project(project)

        assert result is True
        assert not (project / ".brain").exists()

    def test_unlink_removes_generated_rule_files(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that unlink removes generated AI rule files."""
        project = temp_workspace_with_brain / "app"
        project.mkdir()

        config = BrainConfig(workspace_path=temp_workspace_with_brain)
        linker = BrainLinker(config)
        linker.link_project(project, "python-be")

        # All rule files should exist
        for rule_file in AI_RULE_FILES:
            assert (project / rule_file).exists()

        unlink_project(project)

        # All generated rule files should be removed
        for rule_file in AI_RULE_FILES:
            assert not (project / rule_file).exists()

    def test_unlink_preserves_manually_created_files(
        self, temp_workspace_with_brain: Path
    ) -> None:
        """Test that unlink doesn't remove manually created files."""
        project = temp_workspace_with_brain / "app"
        project.mkdir()

        # Create a manual CLAUDE.md without our banner
        (project / "CLAUDE.md").write_text("# My custom instructions\n")

        result = unlink_project(project)

        # Manual file should be preserved
        assert (project / "CLAUDE.md").exists()
        assert "My custom instructions" in (project / "CLAUDE.md").read_text()

    def test_unlink_nonexistent_returns_false(self, tmp_path: Path) -> None:
        """Test that unlinking a project without .brain returns False."""
        result = unlink_project(tmp_path)
        assert result is False
